config/routes.rb
Cal2::Application.routes.draw do
  resources :events do
    member do
      get 'join'
      get 'leave'
      get 'leave_waitlist'
      get 'email_group'
      post 'send_email_group'
    end
  end

  devise_for :users,  :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "registrations" }, :skip => 'sessions' do
    delete "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
  end

  get "/users/:id/calendar" => "user#calendar", as: :calendar
  get "/event" => "events#show"
  root :to => "home#index"

  

end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :title, :location, :teacher, :limit, :course, :year, :start_datetime, :end_datetime, :resources, :tags, :duration, :types, :keywords

  validates :title, :limit, :start_datetime, :end_datetime, presence: :true

  has_many :appointments, dependent: :destroy
  has_many :users, through: :appointments

  has_many :waitlist_appointments, dependent: :destroy
  has_many :waitlist_users, through: :waitlist_appointments, foreign_key: :event_id, class_name: :User
  
  acts_as_taggable_on :tags, :course, :year, :types

  after_update :email_changes
  after_update :check_waitlist

  def duration
    unless self.end_datetime.nil? or self.start_datetime.nil?
      (self.end_datetime - self.start_datetime).to_i / 1.minute
    else
      30
    end
  end

  def color
    if self.course_list.include? "Medical Student"
      "red"
    elsif self.course_list.include? "Nurse Student"
      "green"
    else
      "blue"
    end
  end

  def duration=(val)
    self.end_datetime = self.start_datetime + val.to_i.minute
  end

  def keywords
    self['keywords'].split ","
  end

  def no_remaining_spaces
    self.limit - self.users.count
  end

  def check_waitlist
    if self.users.count < self.limit and self.waitlist_users.count > 0
      user = self.waitlist_users.find(:all, :order => "timestamp ASC").first
      self.waitlist_users.delete(user)
      self.users.append(user)
      UserMailer.off_waitlist_email(user, self).deliver
    end
  end

  def send_email_group(subject, message)
    self.users.each do |user|
      UserMailer.send_email_group(user, subject, message).deliver
    end
  end

  #http://murmurinfo.wordpress.com/2010/11/26/ical-support-for-rails/
  def ical
    e = Icalendar::Event.new
    e.uid = self.id
    e.dtstart = self.start_datetime
    e.dtend = self.end_datetime
    e.summary = self.title
    e.created = self.created_at
    e.location = self.location
    
    e
  end

  def get_bmj_data
    results = []
    self.keywords.each do |tag|
      json = Typhoeus.get "morelikethis.bmj.com/javasim/morelikethis-text.do", params: {index: :corpusIndexExpanded4, text: tag, excl: ''}
      results += JSON.parse json.response_body
    end
    results
  end

  private
  def get_changes
    old_attributes = {'title'=>self.title_was, 'location'=>self.location_was, 'teacher'=>self.teacher_was, 'start_datetime'=>self.start_datetime_was, 'end_datetime'=>self.end_datetime_was, 'resources'=>self.resources_was}
    changes = {}
    self.attributes.each_pair do |key, val|
      unless old_attributes[key] == val or key == "created_at" or key == "updated_at" or key == "id" or not old_attributes.include? (key)
        changes[key] = {old: old_attributes[key], new: val}
      end
    end
    return changes
  end

  def email_changes
    changes = get_changes
    unless changes.empty?
      for user in self.users do
        UserMailer.changes_email(user, self, changes).deliver
      end
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  before_filter :check_privileges!, except: [:index, :show, :join, :leave, :leave_waitlist]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
    @your_events = current_user.events

    unless params[:start].nil? or params[:start].empty? or params[:end].nil? or params[:end].empty?
      start_datetime = Time.iso8601(params[:start])
      end_datetime = Time.iso8601(params[:end])
      @events = @events.where('start_datetime BETWEEN ? AND ?', start_datetime.beginning_of_day, end_datetime.end_of_day)
    end

    unless params[:courses].nil? or params[:courses].empty?
      @events = @events.tagged_with(params[:courses], :on => :course, :any => true)
    end

    unless params[:years].nil? or params[:years].empty?
      @events = @events.tagged_with(params[:years], :on => :year, :any => true)
    end
      
    unless params[:tags].nil? or params[:tags].empty?
      @events = @events.tagged_with(params[:tags], :on => :tags, :any => true)
    end

    unless params[:types].nil? or params[:types].empty?
      @events = @events.tagged_with(params[:types], :on => :types, :any => true)
    end
    
    @events = @events.all

    respond_to do |format|
      format.html
      format.ical
      format.json
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @bmj = @event.get_bmj_data
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    @event.tag_list = event_params[:tag_list].reject { |x| x.empty? }
    @event.year_list = event_params[:year_list].reject { |x| x.empty? }
    @event.course_list = event_params[:course_list].reject { |x| x.empty? }
    @event.type_list = event_params[:type_list].reject { |x| x.empty? }
    @event.save

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render action: 'show', status: :created, location: @event }
      else
        format.html { render action: 'new' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    @event.tag_list = event_params[:tag_list].reject { |x| x.empty? }
    @event.year_list = event_params[:year_list].reject { |x| x.empty? }
    @event.course_list = event_params[:course_list].reject { |x| x.empty? }
    @event.type_list = event_params[:type_list].reject { |x| x.empty? }
    @event.save
    epara = event_params.clone
    epara['start_datetime'] = DateTime.strptime epara['start_datetime'], '%d/%m/%Y %H:%M:%S'
    respond_to do |format|
      if @event.update(epara)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  def join
    @event = Event.find(params[:id])
    respond_to do |format|
      if @event.users.count < @event.limit and not @event.users.include? current_user
        @event.users.append(current_user)
        format.html { redirect_to @event, notice: 'Event successfully joined' }
      else
        @event.waitlist_users.append(current_user)
        format.html { redirect_to @event, notice: 'Event over-subscribed. You have been placed on a waiting list.' }
      end
    end
  end

  def leave
    @event = Event.find(params[:id])
    respond_to do |format|
      if @event.users.include? current_user
        @event.users.delete current_user
        @event.check_waitlist
        format.html { redirect_to @event, notice: 'Event successfully left' }
      else
        format.html { redirect_to @event, notice: "You're not currently a member of this event" }
      end
    end
  end

  def leave_waitlist
    @event = Event.find(params[:id])
    respond_to do |format|
      if @event.waitlist_users.include? current_user
        @event.waitlist_users.delete current_user
        format.html { redirect_to @event, notice: 'Event waiting list successfully left' }
      else
        format.html { redirect_to @event, notice: "You're not currently a member of this event's waiting list" }
      end
    end
  end

  def email_group
    @event = Event.find params[:id]
  end

  def send_email_group
    @event = Event.find params[:id]
    @event.send_email_group params[:subject], params[:body]

    flash[:notice] = 'Email successfully sent.'
    redirect_to @event
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit!
    end

    def check_privileges!
        redirect_to "/", alert: 'You dont have enough permissions to be here' unless current_user.administrator?
    end
end

app/helpers/events_helper.rb
include ActsAsTaggableOn::TagsHelper
module EventsHelper
end

app/views/events/_form.html.erb
<div id="details">
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :location %>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :teacher %>
    <%= f.text_field :teacher %>
  </div>
  <div class="field">
    <%= f.label :limit %>
    <%= f.number_field :limit, {min:0} %>
  </div>

  <div class="field">
    <%= f.label :course %>
    <%= f.select :course_list, COURSES.map{|x| [x,x]}, {}, {:multiple => true} %>
  </div>
  <div class="field">
    <%= f.label :year %>
    <%= f.select :year_list, YEARS.map{|x| [x,x]}, {}, {:multiple => true} %>
  </div>
  <div class="field">
    <%= f.label :types %>
    <%= f.select :type_list, TYPES.map{|x| [x,x]}, {}, {:multiple => true} %>
  </div>


  <div class="field" id="start_datetime">
    <%= f.label :start_datetime %>
    <input data-format='dd/MM/yyyy hh:mm:ss' id="event_start_datetime" name="event[start_datetime]" type="datetime" value="<%=(@event.start_datetime || DateTime.now).strftime('%d/%m/%Y %H:%M:%S')%>">
    <span class="add-on">
      <i data-time-icon="icon-time" data-date-icon="icon-calendar"> </i>
    </span>
  </div>
  <div class="field">
    <%= f.label :duration %>
    <%= f.number_field :duration, {min:0} %>
  </div>

  <div class="field">
    <%= f.label :resources %>
    <%= f.text_area :resources %>
  </div>

  <div class="field">
    <%= f.label :specialties %>
    <%= f.select :tag_list, TAGS.map{|x| [x,x]}, {}, {:multiple => true} %>
  </div>

  <div class="field">
    <%= f.label :keywords %>
    <%= f.text_field :keywords %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/email_group.html.erb
<div id="details">
<%= form_tag send_email_group_event_path(@event) do %>
  <div class="field">
    <%= label_tag :subject %><br>
    <%= text_field_tag :subject %>
  </div>
  <div class="field">
    <%= label_tag :body %><br>
    <%= text_area_tag :body %>
  </div>
  <div class="actions">
    <%= submit_tag "Send" %>
  </div>
<% end %>
</div>

app/views/events/index.html.erb
<% if current_user.administrator? %>
  <%= button_to 'New Event', new_event_path, :method => :get, :class => :btn, :id => :new_event_button %>
<% end %>

<div id="filters_container">
  <div id="filters">
    <div id="filter_title">
      <h2>Filter by:</h2>
    </div>

    <div class="field">
      <%= label :event, :course %><br>
      <%= select :event, :course_list, COURSES.map{|x| [x,x]}, {:selected => current_user.courses}, {:multiple => true} %>
    </div>

    <div class="field">
      <%= label :event, :types %><br>
      <%= select :event, :type_list, TYPES.map{|x| [x,x]}, {}, {:multiple => true} %>
    </div>

    <div class="field">
      <%= label :event, :year %><br>
      <%= select :event, :year_list, YEARS.map{|x| [x,x]}, {:selected => current_user.years}, {:multiple => true} %>
    </div>

    <div class="field">
      <%= label :event, :specialties %><br>
      <%= select :event, :tag_list, TAGS.map{|x| [x,x]}, {}, {:multiple => true} %>
    </div>
  </div>
</div>

<div id="calendar">
</div>

<div class="right_hand_box" id="event_details">
  Mouseover an event to view details
</div>

<div class="right_hand_box" id="your_events">
  <h4>Your upcoming sessions:</h4>
  <ul>
    <% @your_events.each do |event| %>
      <% event_string = "#{event['title']}, #{event['start_datetime']}" %>
      <li><%= link_to event_string, event_path(event) %></li>
    <% end %>
  </ul>
</div>

app/views/events/index.ical.erb
<% @calendar = Icalendar::Calendar.new %>
<% @events.each do |event| %>
  <% @calendar.add event.ical %>
<% end %>
<% @calendar.publish %>
<%= @calendar.to_ical %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<div id="event">
  <br>
  <div id="left"><h2><%= @event.title %></h2></div>
  <div id="start_time"><h4>Start Time: <%= @event.start_datetime.strftime("%b %d, %H:%m") %></h4></div>
  <div id="duration"><h4>Duration: <%= @event.duration %> mins</h4></div>

  <div id="details">
    <% if @event.users.include? current_user %>
      <p>
        You are attending this event
      </p>
    <% elsif @event.waitlist_users.include? current_user %>
      <p>
        You are on the waiting list to attend this event
      </p>
    <% end %>
    <h4>Location: <%= @event.location %></h4>
    <h4>Teacher: <%= @event.teacher %></h4>
    <h4>No. spaces left: <%= @event.no_remaining_spaces %></h4>
    <h4>Info:</h4>
    <h5><%= @event.resources.html_safe %></h5>
    <h4>BMJ Resources:</h4>
    <ul>
      <% for datum in @bmj %>
        <% pres_string = (datum['authors'].nil? ? datum['title'] : "#{datum['title']}, #{datum['authors']}") + " (#{datum['publication']})" %>
        <li><%= link_to pres_string, datum['url'], target: '_blank' %></li>
      <% end %>
    </ul>

    <% if current_user.administrator? and @event.users.count > 0 %>
      <p>
        <strong>Students (<%= @event.users.count %>):</strong>
        <ul>
          <% @event.users.each do |user| %>
            <li><%= user.name %></li>
          <% end %>
        </ul>
      </p>
    <% end %>

    <p>
    <strong>Tags:</strong> <%= @event.keywords.join ", " %>

    <div id="buttons_container">
      <% if @event.users.include? current_user %>
        <%= button_to 'Leave', leave_event_path(@event), :method => :get, :class => :hbutton %>
      <% elsif @event.waitlist_users.include? current_user %>
        <%= button_to 'Leave waiting list', leave_waitlist_event_path(@event), :method => :get, :class => :hbutton %>
      <% else %>
        <%= button_to 'Join', join_event_path(@event), :method => :get, :class => :hbutton, :class => :hbutton %>
      <% end %>
      <% if current_user.administrator? %>
        <%= button_to 'Edit', edit_event_path(@event), :method => :get, :class => :hbutton %>
        <%= button_to 'Email group', email_group_event_path(@event), :method => :get, :class => :hbutton %>
      <% end %>
      <%= button_to 'Back', events_path, :method => :get, :class => :hbutton %>
  </div>
  </div>
</div>