config/routes.rb
Cal2::Application.routes.draw do
  resources :events do
    member do
      get 'join'
      get 'leave'
      get 'leave_waitlist'
      get 'email_group'
      post 'send_email_group'
    end
  end

  devise_for :users,  :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "registrations" }, :skip => 'sessions' do
    delete "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
  end

  get "/users/:id/calendar" => "user#calendar", as: :calendar
  get "/event" => "events#show"
  root :to => "home#index"

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cal2</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag    "fullcalendar", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag    "skins", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag    "sets", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag    "jquery-ui", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag    "jquery.tagit", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

</head>
<body>
  <p id="notice"><%= notice %></p>
  <p id="alert"><%= alert %></p>
  <div class="navbar">
    <div class="navbar-inner">
      <a class="brand" href="/">MEDiCal</a>
      <ul class="nav">
        <% if current_user %>
          <li class="active"><%= link_to "Events", events_path %></li>
          <li><%= link_to "iCal", calendar_path(current_user, :format => :ical) %></li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign in/up", user_omniauth_authorize_path(:google_oauth2) %></li>
        <% end %>
      </ul>
    </div>
  </div>

<%= yield %>

</body>
</html>